#!/bin/bash
# https://github.com/lucasmence
# Based on: https://github.com/daniloancilotto/linux-install-development-script

# startup
sudo apt update -y
sudo apt upgrade -y
sudo ubuntu-drivers autoinstall

# essentials
sudo apt install python3 python3-pip python3-tk python3-dev python3-venv python-is-python3 -y

# vscodium
sudo wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg -O /usr/share/keyrings/vscodium-archive-keyring.asc
echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.asc ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
sudo apt update -y
sudo apt install codium -y
mkdir $HOME/.ssh
codium --install-extension jeanp413.open-remote-ssh
codium --install-extension alefragnani.Bookmarks

# discord
wget -O discord.deb "https://discord.com/api/download?platform=linux&format=deb"
sudo dpkg -i discord.deb
rm discord.deb

# misc
sudo apt install -y chromium kdenetwork-filesharing libreoffice elisa gimp firefox obs-studio

sudo snap install spotify

