#!/bin/bash
# https://github.com/lucasmence

# zoiper
python3 -m venv my-venv
my-venv/bin/pip install gdown
my-venv/bin/gdown 1vDxU8Mo6BYp9VSIgtrN4b8jPYUcq9SdW -O zoiper.deb
sudo dpkg -i zoiper.deb
rm zoiper.deb
rm -r my-venv

# node
sudo snap remove node --purge
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt install nodejs -y

# mysql workbench community
wget https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community_8.0.38-1ubuntu24.04_amd64.deb
sudo dpkg -i mysql-workbench-community_8.0.38-1ubuntu24.04_amd64.deb
rm mysql-workbench-community_8.0.38-1ubuntu24.04_amd64.deb

# misc
sudo apt install -y mysql-client virtualbox filezilla default-libmysqlclient-dev build-essential rabbitmq-server

sudo snap install insomnia
sudo snap install notepad-plus-plus

