#!/bin/bash
# https://github.com/lucasmence
# Script for Kubuntu 24.04 LTS
# 2024, August, 13

FILENAME="userdata.json"
MODULE_SUFIX=".module"
jq -c -r '.modules[]' $FILENAME | while read module; do
    sh "$module$MODULE_SUFIX"
done
if [ $(jq -r '.reboot' $FILENAME) = "true" ]; then
    sudo reboot now
fi
